# Display
GRID_SIZE = 20
TILE_SIZE = 20
FPS = 5

# Agent Energy System
INITIAL_ENERGY = 100
ENERGY_DECAY = 1
ENERGY_GAIN = 30
MAX_ENERGY = 150

# Hydration System
INITIAL_WATER = 100
WATER_DECAY = 1
WATER_GAIN = 30
MAX_WATER = 150

# Food System
FOOD_COUNT = 50
FOOD_REGROWTH_TIME = 30

# Water System
WATER_PATCHES = 1
WATER_PATCH_MAX_SIZE = 5

# Q-Learning Parameters
EPSILON = 0.1
ALPHA = 0.1
GAMMA = 0.9